### ISSUE TITLE
I'm making this mistake, can you fix it?

### ISSUE THREAD

**Issue by alair069** [TheDiamondYT1/TitleManager#1]
[Tesseract] [12:16 am] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'TitleManager v1.0.0': Call to undefined method pocketmine\Player::setTitleDuration() on TheDiamondYT\TitleManager\EventListener
[Tesseract] [12:16 am] CRITICAL> Error: "Call to undefined method pocketmine\Player::setTitleDuration()" (EXCEPTION) in "/plugins/TitleManager-master/src/TheDiamondYT/TitleManager/Main" at line 49

**Comment by TheDiamondYT1** [comment]
Title support was added in newer versions of PocketMine-MP in the [network](https://github.com/pmmp/PocketMine-MP/tree/api3/network) and [blocks](https://github.com/pmmp/PocketMine-MP/tree/api3/blocks) branches.

I suggest making an issue at Tesseract to ask them to implement title support. I could fix it in this plugin, but i dont use Tesseract and therefore dont support it.

**Comment by TheDiamondYT1** [comment]
Also note that i started this plugin yesterday so it is **not done**.

**Comment by alair069** [comment]
I managed to fix it, but now, when I enter the lobby there are no messages

**Comment by TheDiamondYT1** [comment]
@alair069 Yeah, i realised that. I think when `PlayerJoinEvent` is called the player hasnt *technically* spawned yet, so the text doesnt show. 

Any ideas, @dktapps?

**Comment by alair069** [comment]
What is your way of fixing this bug?

**Comment by TheDiamondYT1** [comment]
@alair069 I dont know, i'll wait for @dktapps to reply.

**Comment by alair069** [comment]
Do you have any social networks to talk to?

**Comment by TheDiamondYT1** [comment]
@alair069 Look at https://github.com/TheDiamondYT1/PocketFactions/blob/master/README.md

**Comment by alair069** [comment]
I sent you a message on Twitter, I hope we are friends
